# Docker Compose for development environment

services:
  # 应用服务
  zhuzhen-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zhuzhen-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs  
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://zhuzhen:password123@postgres:5432/zhuzhen_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - zhuzhen-network

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: zhuzhen-postgres
    environment:
      POSTGRES_USER: zhuzhen
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: zhuzhen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - zhuzhen-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: zhuzhen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - zhuzhen-network

volumes:
  postgres_data:
  redis_data:

networks:
  zhuzhen-network:
    driver: bridge